### ISSUE TITLE
extracting feature names

### ISSUE THREAD

**Issue by danielmlow** [nipype/pydra-ml#14]
I'm not able to extract the feature names using pydra. I extract the feature names with this function in `tasks.py`:

```
@pydra.mark.task
@pydra.mark.annotate({"return": {"X": ty.Any, "Y": ty.Any, "groups": ty.Any, "feature_names": ty.Any}})
def read_file(filename, x_indices=None, target_vars=None, group="groups"):
	import pandas as pd

	data = pd.read_csv(filename)
	if isinstance(x_indices[0], int):
		X = data.iloc[:, x_indices]
	elif isinstance(x_indices[0], str):
		X = data[x_indices]
	else:
		raise ValueError(f"{x_indices} is not a list of string or ints")
	Y = data[target_vars]
	if group in data.keys():
		groups = data[:, [group]]
	else:
		groups = np.array(range(X.shape[0]))
	feature_names = np.array(X.columns)
	return X.values, Y.values, groups, feature_names
```

Then in `classifier.py` I understand the variable is added to the wf with `wf.add(read_file(`: 

```
def gen_workflow(inputs, cache_dir=None, cache_locations=None):
    wf = pydra.Workflow(
        name="ml_wf",
        input_spec=list(inputs.keys()),
        **inputs,
        cache_dir=cache_dir,
        cache_locations=cache_locations,
    )
    wf.split(["clf_info", "permute"])
    wf.add(
        read_file(
            name="readcsv",
            filename=wf.lzin.filename,
            x_indices=wf.lzin.x_indices,
            target_vars=wf.lzin.target_vars,
        )
    )
```

Finally I want to input it to the `gen_report()` function so I try this:

```
def run_workflow(wf, plugin, plugin_args):
    cwd = os.getcwd()
    with pydra.Submitter(plugin=plugin, **plugin_args) as sub:
        sub(runnable=wf)
    results = wf.result(return_inputs=True)
    os.chdir(cwd)
    import pickle as pk
    import datetime

    timestamp = datetime.datetime.utcnow().isoformat()
    with open(f"results-{timestamp}.pkl", "wb") as fp:
        pk.dump(results, fp)
    gen_report(results, prefix=wf.name, metrics=wf.inputs.metrics, feature_names=wf.readcsv.lzout.feature_names)
    return results
```

I get the following error when I try to assign feature_names (which is a wf object) to the index of a dataframe:

```
  File "/Users/danielmlow/Dropbox (MIT)/libs/pydra-ml/pydra_ml/report.py", line 33, in shaps_to_summary
    shaps_n_splits.index = feature_names
```

Full error:
```
MacBook-Pro-20:daniel danielmlow$ pydraml -s short-spec.json.sample
2020-05-24 13:06:06,714 [ WARNING] A newer version (0.5) of nipype/pydra is available. You are using 0+unknown
/Users/danielmlow/Dropbox (MIT)/libs/pydra-ml/pydra_ml/report.py:87: UserWarning: There were no FNs, this will output NaNs in the csv and figure for this split column
  warnings.warn(f'There were no {quadrant.upper()}s, this will output NaNs in the csv and figure for this split column')
/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/numpy/core/_methods.py:154: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
Traceback (most recent call last):
  File "/Users/danielmlow/miniconda3/envs/pydra/bin/pydraml", line 11, in <module>
    load_entry_point('pydra-ml', 'console_scripts', 'pydraml')()
  File "/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/danielmlow/Dropbox (MIT)/libs/pydra-ml/pydra_ml/cli.py", line 48, in main
    run_workflow(wf, plugin[0], plugin_args)
  File "/Users/danielmlow/Dropbox (MIT)/libs/pydra-ml/pydra_ml/classifier.py", line 89, in run_workflow
    gen_report(results, prefix=wf.name, metrics=wf.inputs.metrics, feature_names=wf.readcsv.lzout.feature_names)
  File "/Users/danielmlow/Dropbox (MIT)/libs/pydra-ml/pydra_ml/report.py", line 155, in gen_report
    gen_report_shap(results, feature_names, output_dir=output_dir, confusion_matrix=confusion_matrix, plot=plot, plot_top=plot_top)
  File "/Users/danielmlow/Dropbox (MIT)/libs/pydra-ml/pydra_ml/report.py", line 104, in gen_report_shap
    filename=f'shap_{model_name}_{quadrant}', plot=plot, plot_top=plot_top)
  File "/Users/danielmlow/Dropbox (MIT)/libs/pydra-ml/pydra_ml/report.py", line 33, in shaps_to_summary
    shaps_n_splits.index = feature_names
  File "/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/pandas/core/generic.py", line 5287, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/pandas/core/generic.py", line 661, in _set_axis
    self._data.set_axis(axis, labels)
  File "/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 172, in set_axis
    new_labels = ensure_index(new_labels)
  File "/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 5330, in ensure_index
    return Index(index_like, name=index_like.name, copy=copy)
  File "/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 438, in __new__
    subarr = com.asarray_tuplesafe(data, dtype=object)
  File "/Users/danielmlow/miniconda3/envs/pydra/lib/python3.7/site-packages/pandas/core/common.py", line 222, in asarray_tuplesafe
    values = list(values)
TypeError: 'LazyField' object is not iterable
```

**Comment by satra** [comment]
You'll have to assign it to the output of the workflow. See the set output
call.

**Comment by danielmlow** [comment]
Done. I'll leave solution for future reference:
```
	wf.set_output(
		[
			("output", wf.metric.lzout.output),
			("score", wf.metric.lzout.score),
			("shaps", wf.shap.lzout.shaps),
			("feature_names", wf.readcsv.lzout.feature_names)
		]
	)
```

Then feature_names can be accessed through the `results` variable:
```
feature_names = results[0][1].output.feature_names
```
